version: 0.2

env:
  variables:
    CUSTOMER_NAME: ""
    SCRAPE_URLS: ""
    CUSTOMER_LOGO_URL: ""

phases:
  pre_build:
    commands:
      - |
        echo '{
          "scrapeUrls": ["'$SCRAPE_URLS'"],
          "customerName": "'$CUSTOMER_NAME'",
          "customerLogo": "'$CUSTOMER_LOGO_URL'"
        }' > cdk.context.json
  build:
    commands:
      - npm install
      - npx cdk deploy --all --require-approval never

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
