version: 0.2

env:
  variables:
    CUSTOMER_NAME: ""
    SCRAPE_URLS: ""
    CUSTOMER_LOGO_URL: ""
    BEDROCK_ASSUME_ROLE_ARN: ""
    OPENAI_API_KEY: ""
    CUSTOMER_FAVICON_URL: ""
    CUSTOMER_INDUSTRY: ""

phases:
  pre_build:
    commands:
      - |
        echo '{
          "scrapeUrls": ["'$SCRAPE_URLS'"],
          "customerName": "'$CUSTOMER_NAME'",
          "customerLogo": "'$CUSTOMER_LOGO_URL'",
          "bedrockRoleARN": "'$BEDROCK_ASSUME_ROLE_ARN'",
          "customerFavicon": "'$CUSTOMER_FAVICON_URL'",
          "openAIAPIKey": "'$OPENAI_API_KEY'",
          "customerIndustry": "'$CUSTOMER_INDUSTRY'"
        }' > cdk.context.json
      - cat cdk.context.json
  build:
    commands:
      - npm install
      - npx cdk deploy --all --require-approval never

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
